services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database
    ports:
      - "5432:5432"

  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config

  questapi-app:
    build:
      context: ../quest-api
      dockerfile: Dockerfile
    container_name: questapi-app
    depends_on:
      - postgres
      - mqtt-broker
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/database
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      QUESTAPI_MQTT_BROKER_URL: tcp://mqtt-broker:1883
    ports:
      - "8080:8080"

  quest-ui:
    build:
      context: ../quest-ui
      dockerfile: Dockerfile
    container_name: quest-ui
    depends_on:
      - questapi-app
    ports:
      - "3000:3000"
