export const fetchQuizzes = async () => {
  return [
    {
      id: '1',
      title: 'Java quiz',
      description: 'Some questions about Java',
      quizImage: 'https://via.placeholder.com/300',
      questionCount: 10,
      time: 15,
      category: 'Test questions',
      authorName: 'Danylo',
      avatar: 'https://via.placeholder.com/40',
      progress: 80,
    },
    {
      id: '2',
      title: 'Some quiz',
      description: 'Very interest quiz',
      quizImage: 'https://via.placeholder.com/300',
      questionCount: 15,
      time: 20,
      category: 'Question with a picture',
      authorName: 'Unknown',
      avatar: 'https://via.placeholder.com/40',
      progress: 80,
    },
    {
      id: '3',
      title: 'Some quiz',
      description: 'Very interest quiz',
      quizImage: 'https://via.placeholder.com/300',
      questionCount: 15,
      time: 20,
      category: 'Question with a picture',
      authorName: 'Unknown',
      avatar: 'https://via.placeholder.com/40',
      progress: 80,
    },
    {
      id: '4',
      title: 'Some quiz',
      description: 'Very interest quiz',
      quizImage: 'https://via.placeholder.com/300',
      questionCount: 15,
      time: 20,
      category: 'Question with a picture',
      authorName: 'Unknown',
      avatar: 'https://via.placeholder.com/40',
      progress: 80,
    },
  ];
};
