spring:
  application:
    name: quest-api
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: 5MB

questapi:
  security:
    secret-key: "6F9C3D8A7E5B1C46D2F0A3789B4E65CD821F3B07C9D45A6E13F28B07D65C4E9A"
    expiration: 86400000
    allowed-origins:
      - "http://localhost:4373"
    allowed-methods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "OPTIONS"
    allowed-headers:
        - "*"
