spring:
  application:
    name: quest-api
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: "no.reply.questapi@gmail.com"
    password: ""
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

questapi:
  security:
    secret-key: "6F9C3D8A7E5B1C46D2F0A3789B4E65CD821F3B07C9D45A6E13F28B07D65C4E9A"
    expiration: 86400000
    allowed-origins:
      - "http://localhost:3000"
    allowed-methods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "OPTIONS"
    allowed-headers:
        - "*"
  mqtt:
    broker-url: tcp://localhost:1883
    client-id: quiz-service
    default-topic: quiz/events
    qos: 1
    clean-session: true
    topics:
      - quiz/#
  cloud-storage:
    bucket-name: backdoor-unique
    folder: quest-content
    google-application-credential: google-auth.json
    file-size-mb: 5
  url:
    ui: http://localhost:3000